version: '2'

networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.16.0/24
        gateway: 192.168.16.1

services:

  dynomite-dyn_001:
    build: "app/dynomite"
    ports:
      - "8101:8101"
      - "9101:9101"
      - "2101:2101"
      - "3101:3101"
      - "7101:8080"
    depends_on:
      - "redis-server_001"
    networks:
      - public
    volumes:
      - ".:/opt/dynomite/etc"

  redis-server_001:
    image: "redis:5.0"
    ports:
      - "6101:6379"
    networks:
      - public
